name: Pull Requests

on:
  pull_request:
    branches:
      - main
      - track/**

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@fix/charm-pull-charmcraft-channel
    secrets: inherit
    with:
      automatically-retry-hooks: true # A fix for #8
      provider: 'microk8s'
      charmcraft-channel: 'latest/beta'
