name: Release Charm

on:
  push:
    branches:
      - main
      - track/**

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@v1
    secrets: inherit
    with:
      default-track: 2
      automatically-retry-hooks: true # A fix for #8